// Generated by gencpp from file PID/FloatArr.msg
// DO NOT EDIT!


#ifndef PID_MESSAGE_FLOATARR_H
#define PID_MESSAGE_FLOATARR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace PID
{
template <class ContainerAllocator>
struct FloatArr_
{
  typedef FloatArr_<ContainerAllocator> Type;

  FloatArr_()
    : v(0.0)
    , theta(0.0)  {
    }
  FloatArr_(const ContainerAllocator& _alloc)
    : v(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef float _v_type;
  _v_type v;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::PID::FloatArr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::PID::FloatArr_<ContainerAllocator> const> ConstPtr;

}; // struct FloatArr_

typedef ::PID::FloatArr_<std::allocator<void> > FloatArr;

typedef boost::shared_ptr< ::PID::FloatArr > FloatArrPtr;
typedef boost::shared_ptr< ::PID::FloatArr const> FloatArrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::PID::FloatArr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::PID::FloatArr_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace PID

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'PID': ['/home/dvb/dvb/DaVinciBot-FrenchRoboticsCup-2020/cdr_robot_ws/src/PID/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::PID::FloatArr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::PID::FloatArr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::PID::FloatArr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::PID::FloatArr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::PID::FloatArr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::PID::FloatArr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::PID::FloatArr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5efdc7608f256f976ad7573b0f4e032";
  }

  static const char* value(const ::PID::FloatArr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5efdc7608f256f9ULL;
  static const uint64_t static_value2 = 0x76ad7573b0f4e032ULL;
};

template<class ContainerAllocator>
struct DataType< ::PID::FloatArr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PID/FloatArr";
  }

  static const char* value(const ::PID::FloatArr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::PID::FloatArr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 v\n\
float32 theta\n\
";
  }

  static const char* value(const ::PID::FloatArr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::PID::FloatArr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FloatArr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::PID::FloatArr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::PID::FloatArr_<ContainerAllocator>& v)
  {
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PID_MESSAGE_FLOATARR_H
