// Generated by gencpp from file bot_coordinates/Coordinates.msg
// DO NOT EDIT!


#ifndef BOT_COORDINATES_MESSAGE_COORDINATES_H
#define BOT_COORDINATES_MESSAGE_COORDINATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bot_coordinates
{
template <class ContainerAllocator>
struct Coordinates_
{
  typedef Coordinates_<ContainerAllocator> Type;

  Coordinates_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , xdot(0.0)
    , ydot(0.0)
    , thetadot(0.0)  {
    }
  Coordinates_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , xdot(0.0)
    , ydot(0.0)
    , thetadot(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef float _xdot_type;
  _xdot_type xdot;

   typedef float _ydot_type;
  _ydot_type ydot;

   typedef float _thetadot_type;
  _thetadot_type thetadot;





  typedef boost::shared_ptr< ::bot_coordinates::Coordinates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bot_coordinates::Coordinates_<ContainerAllocator> const> ConstPtr;

}; // struct Coordinates_

typedef ::bot_coordinates::Coordinates_<std::allocator<void> > Coordinates;

typedef boost::shared_ptr< ::bot_coordinates::Coordinates > CoordinatesPtr;
typedef boost::shared_ptr< ::bot_coordinates::Coordinates const> CoordinatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bot_coordinates::Coordinates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bot_coordinates::Coordinates_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bot_coordinates

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'bot_coordinates': ['/home/dvb/dvb/DaVinciBot-FrenchRoboticsCup-2020/cdr_robot_ws/src/bot_coordinates/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bot_coordinates::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot_coordinates::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_coordinates::Coordinates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_coordinates::Coordinates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_coordinates::Coordinates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_coordinates::Coordinates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bot_coordinates::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d278de612384af14d52c03a0922c6a31";
  }

  static const char* value(const ::bot_coordinates::Coordinates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd278de612384af14ULL;
  static const uint64_t static_value2 = 0xd52c03a0922c6a31ULL;
};

template<class ContainerAllocator>
struct DataType< ::bot_coordinates::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bot_coordinates/Coordinates";
  }

  static const char* value(const ::bot_coordinates::Coordinates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bot_coordinates::Coordinates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 theta\n\
float32 xdot\n\
float32 ydot\n\
float32 thetadot\n\
";
  }

  static const char* value(const ::bot_coordinates::Coordinates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bot_coordinates::Coordinates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.xdot);
      stream.next(m.ydot);
      stream.next(m.thetadot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Coordinates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bot_coordinates::Coordinates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bot_coordinates::Coordinates_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "xdot: ";
    Printer<float>::stream(s, indent + "  ", v.xdot);
    s << indent << "ydot: ";
    Printer<float>::stream(s, indent + "  ", v.ydot);
    s << indent << "thetadot: ";
    Printer<float>::stream(s, indent + "  ", v.thetadot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOT_COORDINATES_MESSAGE_COORDINATES_H
